# Generated by Django 4.0.4 on 2022-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default=None, max_length=200)),
                ('price', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
