# Generated by Django 4.0.4 on 2022-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('price', models.CharField(max_length=254)),
                ('quantity', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
