# Generated by Django 4.0.3 on 2022-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dish_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
