# Generated by Django 4.0.3 on 2022-05-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_image_dish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dish_category',
        ),
    ]
